theme = "cyberpunk"

[editor]
auto-format = true
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[keys.normal]
# General hx usage
C-p = "file_picker"
C-z = [":vsplit-new", ":config-open"]
C-f = ":format"

[keys.normal.space]
"`" = ":o ~/.config/helix/snippets"

[keys.normal.space.z]
t = ":sh go test -short -timeout 5s $(pwd)/..."
j = ":sh gomodifytags -add-tags json -all -quiet -file %{buffer_name} -w"


[keys.insert.j]
j = "normal_mode"
k = "normal_mode"

[keys.insert.k]
j = "normal_mode"
k = "normal_mode"
