" Author: Max Lay
" Taken from https://github.com/kalda341/dotfiles/blob/master/editors/vim/vimrc

syntax on
set nocompatible 

filetype on
filetype plugin on

set shell=/bin/bash

"Easy ways of getting into normal mode
inoremap kk <ESC>
inoremap jj <ESC>
let mapleader = "\<Space>"

"Load plugins
call plug#begin('~/.local/share/nvim/plugged')
"Theme
Plug 'dracula/vim', { 'as': 'dracula' }

"Syntax Highlighting
"React development
Plug 'pangloss/vim-javascript'
Plug 'maxmellon/vim-jsx-pretty'
"File browser
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
"For commenting lines
Plug 'scrooloose/nerdcommenter'
"For dealing with surrounds (Changing surrounding delimiters)
Plug 'tpope/vim-surround' 
"Integration with tmux windows
Plug 'christoomey/vim-tmux-navigator'

"Autocomplete
Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'
" enable ncm2 for all buffers
autocmd BufEnter * call ncm2#enable_for_buffer()
" IMPORTANT: :help Ncm2PopupOpen for more information
set completeopt=noinsert,menuone,noselect
"Javascript completion
Plug 'ncm2/ncm2-tern',  {'do': 'npm install'}
"Python completion
Plug 'ncm2/ncm2-jedi'
"Go completion
Plug 'ncm2/ncm2-go'
"Rust completion
Plug 'ncm2/ncm2-racer'
"Util completion
Plug 'ncm2/ncm2-bufword'
Plug 'ncm2/ncm2-path'

Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'

call plug#end()

"Theme
set background=dark
set t_Co=256
colorscheme dracula

set history=200

"Use Shif+TAB to select autocomplete menu
inoremap <expr> <S-Tab> pumvisible() ? "\<C-n>" : "\<Tab>"

"Indentation and tabs
" Use two space tabs for html templates
autocmd FileType html setlocal shiftwidth=2 tabstop=2
autocmd FileType hbs setlocal shiftwidth=2 tabstop=2

set expandtab
set softtabstop=2
set shiftwidth=2
set autoindent

"Indent entire document
map <Leader><C-i> mzgg=G'z

"Reload file if edits happen somewhere else
set autoread

"Statusline stuff
"Display status line always
set laststatus=2
set ruler
set showcmd
set ch=1

"Ignore some file types
set wildmenu                    " Cool cmd completion
set wildignorecase
"%% is directory containing current file
cabbr <expr> %% expand('%:p:h')
set wildignore+=.hg,.git,.svn   " Version control
set wildignore+=*.pyc           " Python byte code
set wildignore+=*.beam           " Erlang byte code
set wildignore+=*.jpg,*.bmp,*.gif,*.png,*.jpeg
set wildignore+=*.class,*.o

"Display whitespace
set listchars=tab:->,trail:~,extends:>,precedes:<
set list

"Line numbers and limits
set number                      " Show line numbers
set cursorline

"Movement
set scrolloff=20                 " Start scrolling n lines before border

"Scroll wrapped lines normally
noremap  <buffer> <silent> k gk
noremap  <buffer> <silent> j gj

"End of line
inoremap <C-e> <C-o>$
"Start of line
inoremap <C-a> <C-o>^

"Search
set hlsearch                    " Highlight searches
set incsearch                   " Highlight dynamically as pattern is typed
set ignorecase                  " Ignore case of searches
nmap <Leader>/ :nohlsearch<CR>

"Allows undo after file is closed
if exists("&undodir")
    set undofile
    set undodir=/tmp
endif
"Swap files and backup are super annoying. I save often
set noswapfile
set nobackup

"Set cursorcolumn
nmap <Leader>scc :set cuc<CR>
nmap <Leader>Scc :set nocuc<CR>

"Buffers
noremap <silent><Leader>bp :bprevious<CR>
noremap <silent><Leader>bn :bnext<CR>
noremap <silent><Leader>bc :bd<CR>

"Tabs
map <leader>tn :tabnew<cr>
map <leader>to :tabonly<cr>
map <leader>tc :tabclose<cr>
map <leader>tm :tabmove

"Make it easier to navigate windows
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

"Vimrc stuff
nmap <silent> <Leader>ev :tabe ~/.config/nvim/init.vim<CR>
nmap <silent> <Leader>sv :so ~/.config/nvim/init.vim<CR>
nmap <silent> <Leader>pi :PlugInstall<CR>
nmap <silent> <Leader>pc :PlugClean<CR>

"Newline
map <Leader>o o<Esc>
map <Leader>O O<Esc>

"Copy, paste and cut to system clipboard
map <Leader>y "+y
map <Leader>x "+d
map <Leader>p :set paste<CR>"+p:set nopaste<CR>
map <Leader>P :set paste<CR>"+P:set nopaste<CR>
"Copy to end of line
noremap Y y$

"Use ; as :
nnoremap ; :

"Saving
nmap <Leader>w :w!<cr>
"Sudo write
cmap w!! w !sudo tee % >/dev/null

"cd
map <Leader>cd :cd %:p:h<cr>:pwd<cr>

"Use local config if available
if filereadable("~/.vimrc.local")
    so ~/.vimrc.local
endif
